suthesh-eu footer content update
binary-com/deriv-com pull request #1059
Opened 2020-09-01 03:16 UTC by suthesan-deriv

# Description

Updated eu footer content and links

Changes:

-   Updated eu footer content and links

## Type of change

-   [x] Bug fix
-   [ ] New feature
-   [ ] Update feature
-   [ ] Refactor code
-   [ ] Translation to code
-   [ ] Translation to crowdin
-   [ ] Script configuration
-   [ ] Improve performance
-   [ ] Style only
-   [ ] Dependency update
-   [ ] Documentation update
-   [ ] Release

2020-09-01 07:36 UTC, sara-fs approved these changes

2020-09-02 08:11 UTC, arash-fs approved these changes

2020-09-04 03:19 UTC, mustofa-binary requested changes
please help to resolve conflict

2020-09-22 04:00 UTC, mustofa-binary requested changes

2020-09-22 04:00 UTC, mustofa-binary commented on src/components/layout/footer.js
> -                                        translate_text="Products offered on Deriv.com are not available to clients residing in the EU and are accessible on <0>Binary.com.<0>"
Please add this back

2020-09-22 05:16 UTC, closed without merging