Sean/'In the words of our employees' / testimonial section
binary-com/deriv-com pull request #1135
Opened 2020-10-13 09:44 UTC by sean-binary

# Description

Summary
- Added testimonial section along with mobile layout

Changes:
- Added back the testimonial section
- Updated with new people
- Added layout for mobile

## Type of change

-   [ ] Bug fix
-   [ ] New feature
-   [x] Update feature
-   [ ] Refactor code
-   [ ] Translation to code
-   [ ] Translation to crowdin
-   [ ] Script configuration
-   [ ] Improve performance
-   [ ] Style only
-   [ ] Dependency update
-   [ ] Documentation update
-   [ ] Release

2020-10-13 16:51 UTC, sara-fs submitted a review, later dismissed

2020-10-15 06:15 UTC, mustofa-binary requested changes

2020-10-15 06:15 UTC, mustofa-binary commented on src/pages/careers/_employee-testimonial-carousel.js
> +    img_alt: localize('Ahmad - Recovery Analyst'),
please remove localize function here

2020-10-15 06:15 UTC, mustofa-binary commented on src/pages/careers/_employee-testimonial-carousel.js
> +    img_alt: localize('Lalitaditya - DevOps Engineer'),
here too, and others below

2020-10-15 06:19 UTC, sean-binary commented on src/pages/careers/_employee-testimonial-carousel.js
> +    img_alt: localize('Ahmad - Recovery Analyst'),
Alright noted

2020-10-15 06:19 UTC, sean-binary commented on src/pages/careers/_employee-testimonial-carousel.js
> +    img_alt: localize('Lalitaditya - DevOps Engineer'),
Alright noted

2020-10-15 06:43 UTC, mustofa-binary approved these changes

2020-12-31 07:37 UTC, closed without merging