Kevin/fix:interim translation issue (styling)
binary-com/deriv-com pull request #1142
Opened 2020-10-15 02:13 UTC by kevinw-binary

# Description

Summary

Changes:

-   Fix translation styling issue on interim page 

## Type of change

-   [ ] Bug fix
-   [ ] New feature
-   [ ] Update feature
-   [ ] Refactor code
-   [ ] Translation to code
-   [ ] Translation to crowdin
-   [ ] Script configuration
-   [ ] Improve performance
-   [x] Style only
-   [ ] Dependency update
-   [ ] Documentation update
-   [ ] Release

2020-10-15 06:08 UTC, mustofa-binary submitted a review, later dismissed

2020-10-16 06:22 UTC, mustofa-binary approved these changes

2020-10-16 06:23 UTC, mustofa-binary requested changes
its a translation hotfix, please based it on crowdin

2020-10-19 09:09 UTC, kevinw-binary commented
> its a translation hotfix, please based it on crowdin

Do we need to push it to crowdin even though there's no `Text` change from `message.json`?
I thought if it's only styling issue we don't need to push it to crowdin

2020-10-20 04:01 UTC, mustofa-binary approved these changes

2021-09-06 02:22 UTC, closed without merging