suthesh/fix live chat email auto population on login
binary-com/deriv-com pull request #1151
Opened 2020-10-21 04:23 UTC by suthesan-deriv

# Description

Auto populate email field of client upon login for CS team 

Changes:

-   Auto populate email field of client upon login for CS team 

## Type of change

-   [x] Bug fix
-   [ ] New feature
-   [ ] Update feature
-   [ ] Refactor code
-   [ ] Translation to code
-   [ ] Translation to crowdin
-   [ ] Script configuration
-   [ ] Improve performance
-   [ ] Style only
-   [ ] Dependency update
-   [ ] Documentation update
-   [ ] Release

2020-10-21 06:16 UTC, mustofa-binary approved these changes

2020-11-11 08:32 UTC, mustofa-binary requested changes
test is failing

2020-11-11 08:34 UTC, mustofa-binary requested changes

2020-11-11 08:34 UTC, mustofa-binary commented on src/components/layout/livechat.js
> +import * as CustomerSDK from '@livechat/customer-sdk'
can we only import the function we need 

```suggestion
import { init } from '@livechat/customer-sdk'
```

2020-11-11 08:34 UTC, mustofa-binary commented on src/components/layout/livechat.js
> +    const checkCookie = function () {
we can use arrow anonymous function here

2020-11-11 08:34 UTC, mustofa-binary commented on src/components/layout/livechat.js
> +                                    console.log(response) //eslint-disable-line
console log 😅

2020-11-11 08:35 UTC, mustofa-binary commented on src/components/layout/livechat.js
> +        clientId: '66aa088aad5a414484c1fd1fa8a5ace7',
can store these on utility

2020-12-04 08:25 UTC, kevinw-binary requested changes
Please help resolve confilcts

2020-12-10 09:23 UTC, mustofa-binary approved these changes

2020-12-14 02:41 UTC, kevinw-binary approved these changes

2020-12-14 02:41 UTC, merged