Suthesh/margin trading page update
binary-com/deriv-com pull request #1208
Opened 2020-11-18 06:51 UTC by suthesan-deriv

# Description

Update contents of margin trading page

Changes:

-   Update contents of margin trading page

## Type of change

-   [ ] Bug fix
-   [ ] New feature
-   [x] Update feature
-   [ ] Refactor code
-   [ ] Translation to code
-   [ ] Translation to crowdin
-   [ ] Script configuration
-   [ ] Improve performance
-   [ ] Style only
-   [ ] Dependency update
-   [ ] Documentation update
-   [ ] Release

2020-11-19 05:59 UTC, mustofa-binary approved these changes

2020-12-02 06:52 UTC, mustofa-binary requested changes
please rebase

2020-12-04 08:27 UTC, kevinw-binary requested changes
Please help rebase / resolve merge conflicts

2021-01-07 07:12 UTC, mustofa-binary requested changes
conflicts, please rebase

2021-01-21 02:56 UTC, mustofa-binary approved these changes

2021-01-21 02:57 UTC, merged