suthesh/fix-seo-description
binary-com/deriv-com pull request #1216
Opened 2020-11-20 02:33 UTC by suthesan-deriv

# Description

update SEO descriptions, title and remove keywords tag from all pages

Changes:

-   ...

## Type of change

-   [x] Bug fix
-   [ ] New feature
-   [x] Update feature
-   [ ] Refactor code
-   [ ] Translation to code
-   [ ] Translation to crowdin
-   [ ] Script configuration
-   [ ] Improve performance
-   [ ] Style only
-   [ ] Dependency update
-   [ ] Documentation update
-   [ ] Release

2020-11-20 07:35 UTC, mustofa-binary approved these changes

2020-12-02 04:26 UTC, mustofa-binary requested changes
there is a decrease in accessibility and seo, please help to investigate

2020-12-04 08:16 UTC, kevinw-binary requested changes
please rebase to master

2021-01-19 13:14 UTC, mustofa-binary requested changes
please help to rebase

2021-01-21 02:57 UTC, mustofa-binary approved these changes

2021-01-21 02:58 UTC, merged