Sean/trading responsibly page not accessible
binary-com/deriv-com pull request #1229
Opened 2020-11-25 05:28 UTC by sean-binary

# Description

Summary

Changes:

-   Refactor to use SVGR syntax

## Type of change

-   [x] Bug fix
-   [ ] New feature
-   [ ] Update feature
-   [ ] Refactor code
-   [ ] Translation to code
-   [ ] Translation to crowdin
-   [ ] Script configuration
-   [ ] Improve performance
-   [ ] Style only
-   [ ] Dependency update
-   [ ] Documentation update
-   [ ] Release

2020-11-25 07:51 UTC, mustofa-binary requested changes

2020-11-25 07:51 UTC, mustofa-binary commented on src/pages/responsible-trading/_trading-responsibly.js
> +import { ReactComponent as Info } from 'images/svg/info.svg'
can we use img tag here instead?

2020-11-25 08:02 UTC, sean-binary commented on src/pages/responsible-trading/_trading-responsibly.js
> +import { ReactComponent as Info } from 'images/svg/info.svg'
Sure

2020-11-26 03:22 UTC, mustofa-binary approved these changes

2020-11-26 03:22 UTC, merged