Mahdi Aryayi / Fixed CFD risk value
binary-com/deriv-com pull request #1343
Opened 2021-01-07 13:19 UTC by mahdiaryayi-fs

# Description

Changed CFD risk value from 74% to 71% and changed some contents in the footer.

Changes:

 - Changed CFD risk from 74% to 71%
 - Changed some content in the footer

-   ...

## Type of change

-   [x] Bug fix
-   [ ] New feature
-   [ ] Update feature
-   [ ] Refactor code
-   [ ] Translation to code
-   [ ] Translation to crowdin
-   [ ] Script configuration
-   [ ] Improve performance
-   [ ] Style only
-   [ ] Dependency update
-   [ ] Documentation update
-   [ ] Release

2021-01-07 14:17 UTC, reza-fs approved these changes

2021-01-11 04:24 UTC, mustofa-binary requested changes
please change the base for this to crowdin

2021-01-18 13:30 UTC, mahdiaryayi-fs commented
> please change the base for this to crowdin

I changed the base branch

2021-01-18 14:51 UTC, mustofa-binary approved these changes

2021-01-18 14:51 UTC, merged