update:story and partner numbers jan 2021
binary-com/deriv-com pull request #1345
Opened 2021-01-11 05:56 UTC by kevinw-binary

# Description

Summary

Changes:

-   ...

## Type of change

-   [ ] Bug fix
-   [ ] New feature
-   [x] Update feature
-   [ ] Refactor code
-   [ ] Translation to code
-   [x] Translation to crowdin
-   [ ] Script configuration
-   [ ] Improve performance
-   [ ] Style only
-   [ ] Dependency update
-   [ ] Documentation update
-   [ ] Release

2021-01-12 04:23 UTC, sean-binary approved these changes

2021-01-12 05:39 UTC, yashim-deriv approved these changes

2021-01-19 13:09 UTC, mustofa-binary requested changes
please help to rebase branch

2021-01-20 03:39 UTC, mustofa-binary approved these changes

2021-01-20 03:39 UTC, merged