Kevin/feat:add landing page clone with adjustment
binary-com/deriv-com pull request #1374
Opened 2021-01-21 05:55 UTC by kevinw-binary

# Description

Summary

Changes:

-   ...

## Type of change

-   [ ] Bug fix
-   [x] New feature
-   [ ] Update feature
-   [ ] Refactor code
-   [ ] Translation to code
-   [ ] Translation to crowdin
-   [ ] Script configuration
-   [ ] Improve performance
-   [ ] Style only
-   [ ] Dependency update
-   [ ] Documentation update
-   [ ] Release

2021-01-21 07:13 UTC, sean-binary approved these changes

2021-01-21 07:14 UTC, sean-binary requested changes

2021-01-21 07:14 UTC, sean-binary commented on src/pages/landing/index.js
> +        <Layout is_ppc_redirect={true} is_ppc={true}>
Please add the `no_index` flag

2021-01-21 07:17 UTC, sean-binary requested changes

2021-01-21 07:17 UTC, sean-binary commented on src/pages/landing/index.js
> +        <Layout is_ppc_redirect={true} is_ppc={true}>
I think you should include the `SEO` component here just with the `no_index` flag.

2021-01-21 07:41 UTC, sean-binary submitted a review, later dismissed

2021-01-26 01:53 UTC, yashim-deriv approved these changes

2021-02-05 02:26 UTC, mustofa-binary reviewed
is there any new texts addition to this PR?

2021-02-05 02:29 UTC, kevinw-binary commented
> is there any new texts addition to this PR?

I don't think there's any, it only remove some text

2021-02-05 03:04 UTC, mustofa-binary approved these changes

2021-02-05 03:04 UTC, merged