Sean / fix: belarus office location not centered in mobile
binary-com/deriv-com pull request #1395
Opened 2021-02-01 09:15 UTC by sean-binary

Changes:

-   Update Belarus office link

## Type of change

-   [x] Bug fix
-   [ ] New feature
-   [ ] Update feature
-   [ ] Refactor code
-   [ ] Translation to code
-   [ ] Translation to crowdin
-   [ ] Script configuration
-   [ ] Improve performance
-   [ ] Style only
-   [ ] Dependency update
-   [ ] Documentation update
-   [ ] Release

2021-02-01 09:23 UTC, yashim-deriv approved these changes

2021-02-01 10:44 UTC, AbdallaMourad approved these changes

2021-02-05 02:27 UTC, mustofa-binary approved these changes

2021-02-05 02:28 UTC, mustofa-binary requested changes
Please help to resolve the conflict

2021-02-05 02:40 UTC, mustofa-binary approved these changes

2021-02-05 02:40 UTC, merged