suthesh/pushwoosh-double-subscription
binary-com/deriv-com pull request #1542
Opened 2021-03-22 01:32 UTC by suthesan-deriv

Changes:

-   prevent pushwoosh duplicate subscriptions

## Type of change

-   [x] Bug fix
-   [ ] New feature
-   [ ] Update feature
-   [ ] Refactor code
-   [ ] Translation to code
-   [ ] Translation to crowdin
-   [ ] Script configuration
-   [ ] Improve performance
-   [ ] Style only
-   [ ] Dependency update
-   [ ] Documentation update
-   [ ] Release

2021-03-22 04:53 UTC, mustofa-binary requested changes

2021-03-22 04:53 UTC, mustofa-binary commented on gatsby-browser.js
> +            if (!push_woosh.isSubscribed()){
the function will return a promise, please chain it with then, and use the argument

2021-03-22 08:38 UTC, mustofa-binary approved these changes

2021-03-23 05:45 UTC, yashim-deriv approved these changes

2021-03-23 09:02 UTC, merged