Nuri/update: Updated market page for stocks and indices
binary-com/deriv-com pull request #1679
Opened 2021-04-29 14:02 UTC by njazuli-deriv

Changes:

-   Update stocks and indices sections for market page

## Type of change

-   [ ] Bug fix
-   [ ] New feature
-   [X] Update feature
-   [ ] Refactor code
-   [ ] Translation to code
-   [] Translation to crowdin
-   [ ] Script configuration
-   [ ] Improve performance
-   [ ] Style only
-   [ ] Dependency update
-   [ ] Documentation update
-   [ ] Release

2021-04-29 15:59 UTC, arome-binary requested changes
Hi @njazuli-deriv , from the design the hero graphic is different. Also you may need to replace _images/common/deriv-platform-banner.png_ with phone image found in the design.

2021-04-30 02:30 UTC, njazuli-deriv commented
> Hi @njazuli-deriv , from the design the hero graphic is different. Also you may need to replace _images/common/deriv-platform-banner.png_ with phone image found in the design.

Hi @arome-binary , for footer banner, there will be no changes for this card yet since we are focusing more on `Stocks & Indices` details first.

2021-04-30 03:21 UTC, yashim-deriv commented on src/pages/markets/static/style/_markets-style.js
> +        max-width: ${({ fullwidth }) => (fullwidth ? '80px' : '129px')};
need to be in snake_case

2021-04-30 03:57 UTC, yashim-deriv commented on src/pages/markets/components/helper/_available-trades.js
> +        /* width: 100%; */
```suggestion
```
This probably can be removed

2021-04-30 03:57 UTC, yashim-deriv commented on src/pages/markets/static/content/_margin.js
> +// import { OTCGERMAN } from 'components/elements/symbols'
```suggestion
```
can be removed

2021-04-30 04:50 UTC, njazuli-deriv commented on src/pages/markets/static/style/_markets-style.js
> +        max-width: ${({ fullwidth }) => (fullwidth ? '80px' : '129px')};
fixed in latest commit

2021-04-30 04:51 UTC, njazuli-deriv commented on src/pages/markets/components/helper/_available-trades.js
> +        /* width: 100%; */
removed in latest commit

2021-04-30 04:51 UTC, njazuli-deriv commented on src/pages/markets/components/helper/_available-trades.js
>          background: #f3f3f3;
fixed in latest commit

2021-04-30 04:51 UTC, njazuli-deriv commented on src/pages/markets/components/helper/_available-trades.js
> +        /* width: 100%; */
removed in latest commit

2021-04-30 04:51 UTC, njazuli-deriv commented on src/pages/markets/components/sub-markets/_digital-options.js
> +                <StyledText font_size={'16px'} align="center">
fixed in latest commit

2021-04-30 04:53 UTC, njazuli-deriv commented on src/pages/markets/static/content/_margin.js
> +// import { OTCGERMAN } from 'components/elements/symbols'
removed in latest commit

2021-05-03 03:34 UTC, yashim-deriv submitted a review, later dismissed

2021-05-07 04:55 UTC, sean-binary approved these changes

2021-05-07 04:55 UTC, merged