Kevin/hotfix ibpage signup button
binary-com/deriv-com pull request #1733
Opened 2021-05-20 10:22 UTC by kevinw-binary

Changes:

-   ...

## Type of change

-   [x] Bug fix
-   [ ] New feature
-   [ ] Update feature
-   [ ] Refactor code
-   [ ] Translation to code
-   [ ] Translation to crowdin
-   [ ] Script configuration
-   [ ] Improve performance
-   [ ] Style only
-   [ ] Dependency update
-   [ ] Documentation update
-   [ ] Release

2021-05-20 11:55 UTC, arome-binary reviewed
Hi @kevinw-binary , quick one, what is the task # in redmine?

2021-05-20 12:00 UTC, arome-binary commented
> Hi @kevinw-binary , quick one, what is the task # in redmine?

Seen it, ignore the question.....

2021-05-20 12:07 UTC, arome-binary submitted a review, later dismissed

2021-05-20 13:17 UTC, ShuvoHabib submitted a review, later dismissed
LGTM

2021-05-21 02:02 UTC, sean-binary approved these changes

2021-05-21 02:04 UTC, sean-binary commented on src/components/layout/nav.js
> -const LinkSignupButton = styled(LinkButton)`
It can't be extended from a button as it has the `to` and `external` prop behaving like a localizedlink.

2021-05-21 02:05 UTC, sean-binary requested changes
Left a comment.

2021-05-21 07:25 UTC, sean-binary approved these changes

2021-05-21 13:58 UTC, ShuvoHabib commented on src/components/localization/localized-link.js
>      if (external || external === 'true') {
Can we make it shorter? i.e: if (external) {}

2021-05-21 14:02 UTC, ShuvoHabib commented on src/components/layout/nav.js
> +        opacity: ${(props) => (props.move ? 1 : 0)};
If the reason of this opacity is to hide, perhaps we can use visibility: visible || hidden

2021-05-21 14:02 UTC, ShuvoHabib reviewed
Just a couple of minor feedback

2021-05-23 11:37 UTC, nijil-binary approved these changes

2021-05-23 11:38 UTC, merged