habib | khalid / Forex and stocks ebook LP
binary-com/deriv-com pull request #1778
Opened 2021-06-02 10:00 UTC by Khalidxx

Changes:

-   Added Forex ebook landing page
-   Added Stocks ebook landing page

## Type of change

-   [ ] Bug fix
-   [x] New feature
-   [ ] Update feature
-   [ ] Refactor code
-   [ ] Translation to code
-   [ ] Translation to crowdin
-   [ ] Script configuration
-   [ ] Improve performance
-   [ ] Style only
-   [ ] Dependency update
-   [ ] Documentation update
-   [ ] Release

2021-06-02 15:38 UTC, arome-binary approved these changes
LGTM

2021-06-03 07:10 UTC, arome-binary requested changes

2021-06-03 08:12 UTC, Khalidxx commented on src/pages/landing/ebooks/forex.js
> +            <Introduction
Oh yeah! Fixing it now 👍

2021-06-04 09:19 UTC, mustofa-binary commented on src/components/custom/_agreement-label.js
> +                style={{
```suggestion
                you can expand styled component styled(Checkbox)`
                    ....your style here
                `
```

2021-06-04 09:21 UTC, mustofa-binary commented on src/components/layout/ebooks/get-ebook.js
> +    /* margin-left: 0.8rem; */
👀

2021-06-04 09:43 UTC, sean-binary approved these changes

2021-06-04 09:44 UTC, merged