Nikolai berestevich/fix/besquare date and social media35298
binary-com/deriv-com pull request #1845
Opened 2021-06-18 11:20 UTC by nikolaiberestevich-deriv

Changes:

-   July changed to August
-   fix social medias' css

## Type of change

-   [x ] Bug fix
-   [ ] New feature
-   [ ] Update feature
-   [ ] Refactor code
-   [ ] Translation to code
-   [ ] Translation to crowdin
-   [ ] Script configuration
-   [ ] Improve performance
-   [ ] Style only
-   [ ] Dependency update
-   [ ] Documentation update
-   [ ] Release

2021-06-18 13:38 UTC, arome-binary approved these changes

2021-06-21 10:17 UTC, mustofa-binary requested changes
please revert the change on messages.json

2021-06-21 12:26 UTC, nikolaiberestevich-deriv commented
i changed back to "July" in messages.json

2021-06-22 01:24 UTC, sean-binary approved these changes

2021-06-22 06:53 UTC, mustofa-binary approved these changes

2021-06-22 06:53 UTC, merged