Sean/Remove BeSquare language pages
binary-com/deriv-com pull request #1946
Opened 2021-07-26 09:53 UTC by sean-binary

Changes:

## Type of change

-   [x] Bug fix
-   [ ] New feature
-   [ ] Update feature
-   [ ] Refactor code
-   [ ] Translation to code
-   [ ] Translation to crowdin
-   [ ] Script configuration
-   [ ] Improve performance
-   [ ] Style only
-   [ ] Dependency update
-   [ ] Documentation update
-   [ ] Release

2021-07-26 10:54 UTC, mustofa-binary approved these changes

2021-07-26 10:55 UTC, mustofa-binary requested changes

2021-07-26 10:55 UTC, mustofa-binary commented on gatsby-node.js
>          const careers_regex = /^[a-z-]+\/careers\//g
I think we can create one variable for e.g excluded page and check it from there

2021-07-28 03:03 UTC, yashim-deriv approved these changes
LGTM

2021-07-28 04:28 UTC, mustofa-binary approved these changes
👍

2021-07-29 03:12 UTC, suthesan-deriv approved these changes

2021-07-29 06:51 UTC, merged