Fix: removed real text in instructions
binary-com/deriv-com pull request #2035
Opened 2021-08-22 10:46 UTC by prince-deriv

Changes:

-   ...

## Type of change

-   [ ] Bug fix

2021-08-22 10:51 UTC, mahdiaryayi-fs submitted a review, later dismissed

2021-08-23 01:15 UTC, sean-binary requested changes

2021-08-23 01:15 UTC, sean-binary commented on src/pages/help-centre/deriv-x.js
> +                translate_text="On the <0>Deriv X dashboard</0>, select the account type you want to open (Demo) and click “Add account. Follow the instructions on the screen to create a new Deriv X
```suggestion
                translate_text="On the <0>Deriv X dashboard</0>, select the account type you want to open (Demo) and click “Add account". Follow the instructions on the screen to create a new Deriv X account."
```

2021-08-23 01:18 UTC, sean-binary commented on src/pages/help-centre/deriv-x.js
> +                translate_text="On the <0>Deriv X dashboard</0>, select the account type you want to open (Demo) and click “Add account". Follow the instructions on the screen to create a new Deriv X
```suggestion
                translate_text="On the <0>Deriv X dashboard</0>, select the account type you want to open (Demo) and click “Add account”. Follow the instructions on the screen to create a new Deriv X account."
```

2021-08-23 01:20 UTC, sean-binary commented on src/pages/help-centre/deriv-x.js
> +                translate_text="On the <0>Deriv X dashboard</0>, select the account type you want to open (Demo) and click “Add account". Follow the instructions on the screen to create a new Deriv X
```suggestion
                translate_text="On the <0>Deriv X dashboard</0>, select the account type you want to open (Demo) and click “Add account”. Follow the instructions on the screen to create a new Deriv X account."
```

2021-08-23 01:20 UTC, sean-binary approved these changes

2021-08-23 01:28 UTC, merged