khalid/ID naming
binary-com/deriv-com pull request #2060
Opened 2021-09-01 07:12 UTC by khalid-deriv

Changes:

-   Added a human-readable ID names to all buttons and forms

## Type of change

-   [ ] Bug fix
-   [ ] New feature
-   [ ] Update feature
-   [x] Refactor code
-   [ ] Translation to code
-   [ ] Translation to crowdin
-   [ ] Script configuration
-   [ ] Improve performance
-   [ ] Style only
-   [ ] Dependency update
-   [ ] Documentation update
-   [ ] Release

2021-09-21 06:29 UTC, sean-binary requested changes

2021-09-21 06:29 UTC, sean-binary commented on src/pages/home/_trade-types-mobile.js
> +                    is="dm-trade-types-mobile-signup"
```suggestion
                    id="dm-trade-types-mobile-signup"
```

2021-09-21 06:29 UTC, sean-binary commented on src/pages/p2p/components/_availability.js
> +                                        to="/signup"
```suggestion
                                        to="/signup/"
```

2021-09-21 06:29 UTC, sean-binary commented
Do we ever use the existing ids for styling?

2021-09-24 03:46 UTC, khalid-deriv commented
> Do we ever use the existing ids for styling?
No, we don't I made sure. Godbless styled components 😄 
Let me check again though just to be 100% sure

2021-09-24 03:55 UTC, sean-binary approved these changes

2021-10-01 02:04 UTC, merged