Pavel-Latyshou/on Deriv.com for EU and non-EU there is difference in redirecting pop up to the trading platfrom
binary-com/deriv-com pull request #2234
Opened 2021-11-01 09:00 UTC by pavel-latyshou-deriv

Changes:

-   ...

## Type of change

-   [x ] Bug fix
-   [ ] New feature
-   [ ] Update feature
-   [ ] Refactor code
-   [ ] Translation to code
-   [ ] Translation to crowdin
-   [ ] Script configuration
-   [ ] Improve performance
-   [ ] Style only
-   [ ] Dependency update
-   [ ] Documentation update
-   [ ] Release

2021-11-23 08:34 UTC, sean-binary requested changes

2021-11-23 08:34 UTC, sean-binary commented on src/components/localization/localized-link.js
> -    const { is_eu_country } = useContext(DerivStore)
We still need the modal pop for EU when it is an external link (not deriv product links). You need to move smart trader link onto the array that doesn't have the EU modal.

2021-11-29 02:27 UTC, sean-binary commented on src/components/localization/localized-link.js
> -    const { is_eu_country } = useContext(DerivStore)
Should this not be removed anymore then? @pavel-latyshou-deriv

2021-12-06 07:08 UTC, sean-binary requested changes

2021-12-06 07:08 UTC, sean-binary commented on src/components/localization/localized-link.js
> +        return `${localized_link_url[type]}/${getThaiExcludedLocale(locale)}/${to}.html`
The only change that should be required for the PR should be to add `&& !deriv_other_products.includes(type)` on the conditions for `show_modal` on line 192. `smart_trader` shouldn't be categorised under social platforms.

2021-12-07 01:45 UTC, sean-binary approved these changes

2021-12-10 07:50 UTC, yashim-deriv requested changes
Is there a reason to remove the `is_eu_country` check completely? To fix the redirect modal, you can simply add `!deriv_other_products.includes(type)` to not show modal for that specific case

2023-02-08 03:10 UTC, closed without merging