fiona /  redirect url to dmt5 real account
binary-com/deriv-com pull request #2251
Opened 2021-11-12 08:55 UTC by fiona-deriv

Changes:

-   ...

## Type of change

-   [x] Bug fix
-   [ ] New feature
-   [ ] Update feature
-   [ ] Refactor code
-   [ ] Translation to code
-   [ ] Translation to crowdin
-   [ ] Script configuration
-   [ ] Improve performance
-   [ ] Style only
-   [ ] Dependency update
-   [ ] Documentation update
-   [ ] Release

2021-11-15 01:09 UTC, kevinw-binary submitted a review, later dismissed

2021-11-15 03:25 UTC, sean-binary requested changes

2021-11-15 03:25 UTC, sean-binary commented on src/pages/dmt5/_interest_free_trading.js
> +                    to={deriv_mt5_app_url}
```suggestion
                    type="mt5"
```

2021-11-15 03:25 UTC, sean-binary commented on src/pages/dmt5/_interest_free_trading.js
> +                    to={deriv_mt5_app_url}
This should be set via the `type` instead. You can refer to `localized-link.js` for more info on the current config.

2021-11-23 08:57 UTC, sean-binary approved these changes

2021-11-23 08:57 UTC, merged