Lp fx crowdin2
binary-com/deriv-com pull request #2277
Opened 2021-11-25 14:07 UTC by behnaz-fs

Changes:

-   ...

## Type of change

-   [ ] Bug fix
-   [ ] New feature
-   [ ] Update feature
-   [ ] Refactor code
-   [ ] Translation to code
-   [ ] Translation to crowdin
-   [ ] Script configuration
-   [ ] Improve performance
-   [ ] Style only
-   [ ] Dependency update
-   [ ] Documentation update
-   [ ] Release

2021-11-26 08:57 UTC, sean-binary requested changes

2021-11-26 08:57 UTC, sean-binary commented on src/pages/landing/forex-trading/components/_hero.js
> +`
Pleaase pass these directly to the `tabletS` prop. And please do so whenever possible for the supported properties for components like `Flex`, `Box`, `Container`, `Header` & `Text`.

2021-11-26 08:57 UTC, sean-binary commented on src/pages/landing/forex-trading/components/_hero.js
> +        }
Whenever possible, please try to avoid styling elements in this manner `${ElementName}` as it will override specificity over responsive style props.

2021-11-26 08:57 UTC, sean-binary commented on src/pages/landing/forex-trading/components/_hero.js
> +            <Show.Desktop min_width="800">
We are beginning to deprecate the use of `Show` for desktop and mobile responsive style, especially for components at the top visible at the starting load of the page as it doesn't work well with SSG sites. There will be a split second where the component is visible before being removed from the DOM.

You could instead use `display: none` here or change the background_data with the help of `use-browser-resize` hook.

2021-11-26 08:57 UTC, sean-binary commented on src/pages/landing/forex-trading/index.js
> +const DP2P_CONTENT = [
Please change variable names according to your page content.

2021-11-26 08:57 UTC, sean-binary commented on src/pages/landing/trade-forex/index.js
> +const DP2P_CONTENT = [
Please name the variables accordingly to the content.

2021-11-30 09:23 UTC, closed without merging

2021-11-30 09:26 UTC, behnaz-fs commented
this pr was created for translators and based on crowdin, seems according to the process no need for this