Scroll indicator
binary-com/deriv-com pull request #2282
Opened 2021-11-29 11:02 UTC by pavel-latyshou-deriv

Changes:

-   ...

## Type of change

-   [ ] Bug fix
-   [x ] New feature
-   [ ] Update feature
-   [ ] Refactor code
-   [ ] Translation to code
-   [ ] Translation to crowdin
-   [ ] Script configuration
-   [ ] Improve performance
-   [ ] Style only
-   [ ] Dependency update
-   [ ] Documentation update
-   [ ] Release

2021-11-29 12:34 UTC, habib-deriv approved these changes

2021-11-30 04:17 UTC, sean-binary commented on src/templates/article.js
> +    })
```suggestion
    useEffect(() => {
        const windowScroll = () => {
            window.addEventListener('scroll', scrollFunc)
        }
        windowScroll()
        return () => {
            window.removeEventListener('scroll', scrollFunc)
        }
    }, [])
```

2021-11-30 04:17 UTC, sean-binary commented on src/templates/article.js
> +    })
This should only be run on mount right?

2021-11-30 06:35 UTC, pavel-latyshou-deriv commented on src/templates/article.js
> +    })
Ahh, just forgot about it

2021-11-30 06:36 UTC, pavel-latyshou-deriv commented on src/templates/article.js
> +    })
Thanks!

2021-11-30 07:05 UTC, sean-binary commented on src/pages/academy/blog/posts/_style.js
> +    z-index: 10000;
Let's use the same z-index as our navbars. `100`

2021-11-30 07:09 UTC, sean-binary requested changes
We also need to add this progress bar for `preview/index.js`.

2021-11-30 07:09 UTC, sean-binary commented on src/templates/article.js
> +        windowScroll()
```suggestion
        window.addEventListener('scroll', scrollFunc)
```

2021-11-30 07:09 UTC, sean-binary commented on src/templates/article.js
> +        windowScroll()
Since we're using it right away and only once here. We don't need to declare it as a named function.

2021-11-30 07:09 UTC, sean-binary commented on src/templates/article.js
> +    const scrollElement = useRef(null)
This doesn't look like it is being used.

2021-11-30 08:45 UTC, sean-binary approved these changes

2021-12-09 09:59 UTC, merged