Kevin/hide Smart Trader, Binary bot, Dbot, market-options
binary-com/deriv-com pull request #2477
Opened 2022-01-07 06:37 UTC by kevinw-binary

Changes:

-   ...

## Type of change

-   [ ] Bug fix
-   [ ] New feature
-   [x] Update feature
-   [ ] Refactor code
-   [ ] Translation to code
-   [ ] Translation to crowdin
-   [ ] Script configuration
-   [ ] Improve performance
-   [ ] Style only
-   [ ] Dependency update
-   [ ] Documentation update
-   [ ] Release

2022-01-07 06:45 UTC, sean-binary requested changes

2022-01-07 06:45 UTC, sean-binary commented on src/components/custom/other-platforms.js
> +                {!is_eu_country && (
```suggestion

```
You can remove this since above and below it are the same condition.

2022-01-07 06:45 UTC, sean-binary commented on src/components/elements/off-canvas-menu.js
> +                        {!is_eu_country && (
```suggestion

```

2022-01-07 06:45 UTC, sean-binary commented on src/components/elements/off-canvas-menu.js
> +                        {!is_eu_country && (
```suggestion

```

2022-01-07 06:45 UTC, sean-binary commented on src/pages/markets/components/helper/_available-trades.js
> +
You probably don't need this.

2022-01-10 05:32 UTC, sean-binary submitted a review, later dismissed

2022-01-11 06:41 UTC, kevinw-binary commented
closing this PR since we're planning to release it on crowdin https://github.com/binary-com/deriv-com/pull/2489

2022-01-11 07:30 UTC, closed without merging