Kevin/ hide multiple products for EU
binary-com/deriv-com pull request #2490
Opened 2022-01-11 07:41 UTC by kevinw-binary

Changes:

-   ...

## Type of change

-   [ ] Bug fix
-   [ ] New feature
-   [x] Update feature
-   [ ] Refactor code
-   [ ] Translation to code
-   [ ] Translation to crowdin
-   [ ] Script configuration
-   [ ] Improve performance
-   [ ] Style only
-   [ ] Dependency update
-   [ ] Documentation update
-   [ ] Release

2022-01-14 06:18 UTC, sean-binary requested changes

2022-01-14 06:18 UTC, sean-binary commented on src/components/custom/other-platforms.js
> +                            : localize('Check out our other platforms')}
Please try to avoid these nested ternary calls. We can declare outside a function `getHeaderText` that returns the respective text to avoid these.

2022-01-14 06:18 UTC, sean-binary commented on src/components/custom/other-platforms.js
> +    const { is_eu_country } = React.useContext(DerivStore)
We need to now start using the `EU` / `NonEU` wrapper component from 'visibility.tsx` instead of the `is_eu_country` check here.

2022-01-27 04:29 UTC, habib-deriv approved these changes

2022-01-27 04:36 UTC, sean-binary approved these changes

2022-01-27 04:59 UTC, merged