suthesh/review-fix-about-us
binary-com/deriv-com pull request #2554
Opened 2022-01-24 06:40 UTC by suthesan-deriv

Changes:

-   fixed comments on about-us page

## Type of change

-   [x] Bug fix
-   [ ] New feature
-   [ ] Update feature
-   [ ] Refactor code
-   [ ] Translation to code
-   [ ] Translation to crowdin
-   [ ] Script configuration
-   [ ] Improve performance
-   [ ] Style only
-   [ ] Dependency update
-   [ ] Documentation update
-   [ ] Release

2022-01-24 07:22 UTC, habib-deriv approved these changes

2022-01-26 06:54 UTC, sean-binary requested changes

2022-01-26 06:54 UTC, sean-binary commented on package.json
> +        "embla-carousel-autoplay": "^6.1.1",
Please uninstall this to update the package lock since it is no longer in use.

2022-01-27 04:56 UTC, sean-binary commented on src/pages/who-we-are/_AboutUsBanner.tsx
> +                    <StyledLinkButton secondary="true" to="/careers/" rel="noopener noreferrer">
We only need the `rel` for external links.

2022-01-27 04:57 UTC, sean-binary commented on src/pages/who-we-are/carousel/_Marquee.tsx
> +const ImageMarquee = () => {
Could you also rename the file to match the component name or vice versa?

2022-02-08 03:29 UTC, sean-binary approved these changes

2022-02-08 03:30 UTC, merged