Pavel Latyshou - Improvement card for https://deriv.com/partners/affiliate-ib/ page
binary-com/deriv-com pull request #2609
Opened 2022-02-04 10:23 UTC by pavel-latyshou-deriv

Changes:

-   ...

## Type of change

-   [ ] Bug fix
-   [ ] New feature
-   [ ] Update feature
-   [ ] Refactor code
-   [ ] Translation to code
-   [ ] Translation to crowdin
-   [ ] Script configuration
-   [ ] Improve performance
-   [ x] Style only
-   [ ] Dependency update
-   [ x] Documentation update
-   [ ] Release

2022-02-04 11:18 UTC, habib-deriv approved these changes

2022-02-07 05:10 UTC, alamin-deriv approved these changes

2022-02-11 12:46 UTC, habib-deriv approved these changes

2022-02-23 17:05 UTC, habib-deriv commented on src/components/elements/timeline.js
> +const Timeline = ({ pb, children, ...props }) => {
Instead of pb, let's use a better descriptive name

2022-03-16 05:44 UTC, sean-binary requested changes

2022-03-16 05:44 UTC, sean-binary commented on src/components/elements/timeline.js
> +        padding-bottom: ${(props) => props.pbMobile};
```suggestion
        padding-bottom: ${(props) => props.pb_mobile};
```
variables should be in snake_case.

2022-03-16 05:44 UTC, sean-binary commented on src/components/elements/timeline.js
> +                <FlexWrapper key={idx} is_border={children.length !== idx + 1} pb={paddingBottom}>
Same here.

2022-03-16 05:44 UTC, sean-binary commented on src/pages/partners/affiliate-ib/_deriv-affiliate-programme.tsx
> +                                <Header as="h2" type="paragraph-1" weight="400">
```suggestion
                                <Header as="h2" type="paragraph-1" weight="regular">
```
Let's use regular for consistency. Few other instances below.

2022-03-16 05:44 UTC, sean-binary commented on src/pages/partners/affiliate-ib/_more-reason.tsx
> +
Can we just set for max-width instead? And we can omit this media query.

2022-03-16 05:44 UTC, sean-binary commented on src/pages/partners/affiliate-ib/_partner-cta.tsx
> -        padding-top: 9px;
Button height and width should be controlled via padding instead.

2022-03-16 05:44 UTC, sean-binary commented on src/pages/partners/affiliate-ib/_who-can-apply.tsx
> +    }
Can we use `Header` components instead for styling this?

2022-03-16 05:44 UTC, sean-binary commented on src/pages/partners/affiliate-ib/_who-can-apply.tsx
> +        }
Same here.

2022-03-16 05:44 UTC, sean-binary commented on src/pages/partners/affiliate-ib/_who-can-apply.tsx
> +                                <Header as="h4" type="sub-section-title" mb="8px" lh="1.5">
We shouldn't need to set the `lh` if we use the appropriate type.

2022-03-16 05:44 UTC, sean-binary commented on src/pages/partners/affiliate-ib/index.tsx
> +    }
This looks like it can be avoid if you use the `subtitle-1` type instead. We don't need SubtitleHeader here, just `Header`.

2022-03-16 05:44 UTC, sean-binary commented on src/pages/partners/affiliate-ib/index.tsx
> +    }
Same here. Let's refactor this to use `Header` with the appropriate type.

2022-06-03 08:23 UTC, habib-deriv approved these changes
LGTM

2023-02-08 03:10 UTC, closed without merging