updates on partners/payment-agent
binary-com/deriv-com pull request #2632
Opened 2022-02-11 05:22 UTC by alamin-deriv

Changes:

-   Added the new P2P banner in `partners/payment-agent` page

## Type of change

-   [ ] Bug fix
-   [ ] New feature
-   [x] Update feature
-   [ ] Refactor code
-   [ ] Translation to code
-   [ ] Translation to crowdin
-   [ ] Script configuration
-   [ ] Improve performance
-   [ ] Style only
-   [ ] Dependency update
-   [ ] Documentation update
-   [ ] Release

2022-02-13 18:51 UTC, alamin-deriv commented on src/pages/partners/payment-agent/_p2p_banner.tsx
> +const StyledText = styled(Text)`
I tried changing it to what you suggested but didn't work it just become bold the `Header` and nothing change

2022-02-14 03:40 UTC, sean-binary requested changes

2022-02-14 03:40 UTC, sean-binary commented on src/pages/partners/payment-agent/_p2p_banner.tsx
> +`
Is this any different than the original button component?

2022-02-14 03:40 UTC, sean-binary commented on src/pages/partners/payment-agent/_who-can-apply.tsx
> +`
Widths, max widths, margins should be set on its parent wrapper instead. Font size and line height adjust for responsive shouldn't be needed if the correct `type` is used.

2022-02-14 03:40 UTC, sean-binary commented on src/pages/partners/payment-agent/_who-can-apply.tsx
> +                        <StyledListHeader as="h4" size="1.6rem">
`size` should not be set but instead use `type`.

2022-02-14 03:40 UTC, sean-binary commented on src/pages/partners/payment-agent/_p2p_banner.tsx
> +const StyledText = styled(Text)`
Let's discuss to see why that's the case. Please reach out when you are available.

2022-02-14 06:02 UTC, alamin-deriv commented on src/pages/partners/payment-agent/_p2p_banner.tsx
> +const StyledText = styled(Text)`
No, don't worry, I saw the issue

2022-02-21 17:09 UTC, closed without merging

2022-02-21 17:14 UTC, alamin-deriv commented
@NikitaK-deriv has taken over this task and he has a new [PR](https://github.com/binary-com/deriv-com/pull/2670)