MohammadH/ Homepage crowdin eu uk
binary-com/deriv-com pull request #2658
Opened 2022-02-16 13:28 UTC by mohammad-rework

Changes:

-   Apply EU UK changes to Crowdin Homepage

## Type of change

-   [ ] Bug fix
-   [ ] New feature
-   [x] Update feature
-   [ ] Refactor code
-   [ ] Translation to code
-   [ ] Translation to crowdin
-   [ ] Script configuration
-   [ ] Improve performance
-   [ ] Style only
-   [ ] Dependency update
-   [ ] Documentation update
-   [ ] Release

2022-02-16 14:56 UTC, habib-deriv approved these changes

2022-02-16 16:05 UTC, salarhfz-fs commented on src/components/containers/visibility.tsx
> +            const uk_domains = ['uk', 'staging-uk']
If there is a config file in the project to store constants like these, it's better to move these to the config file.

2022-02-17 01:07 UTC, yashim-deriv commented on src/pages/home/_trade-types.tsx
> +                    : localize('Trade the way you want with 2 exciting trade types')}
```suggestion
                <Localize translate_text="Trade the way you want with {{trade_no}} exciting trade types" values={{ trade_no: is_row ? '3' : '2' }} />
```

There's a better way to handle dynamic text translations as I shown above. You can refer to the `General Implementation Guide` for additional info

2022-02-17 01:07 UTC, yashim-deriv commented on src/pages/home/_trade-types.tsx
> +                        {(is_row ? items_details_cr : items_details_eu_uk).map((item) => {
There are repetition of this statement here and at line 295. Best to set it once and re-use it in both lines.

2022-02-17 01:08 UTC, yashim-deriv requested changes
Added some review comments

2022-02-17 08:12 UTC, prince-deriv approved these changes

2022-02-18 00:59 UTC, yashim-deriv commented on src/pages/home/_our_platforms.tsx
> +                              )}
Can refactor this block to use `<Localize` method as previous review.

2022-02-18 01:00 UTC, yashim-deriv approved these changes
A minor refactor. The rest looks good! 🙌🏼

2022-02-18 05:02 UTC, salarhfz-fs approved these changes

2022-02-24 01:12 UTC, merged