MohammadH/Refactor Testimonial
binary-com/deriv-com pull request #2766
Opened 2022-03-11 14:16 UTC by mohammad-rework

Changes:

-   Refactor Testimonial

## Type of change

-   [ ] Bug fix
-   [ ] New feature
-   [ ] Update feature
-   [x] Refactor code
-   [ ] Translation to code
-   [ ] Translation to crowdin
-   [ ] Script configuration
-   [ ] Improve performance
-   [ ] Style only
-   [ ] Dependency update
-   [ ] Documentation update
-   [ ] Release

2022-03-14 07:14 UTC, sean-binary requested changes

2022-03-14 07:21 UTC, mohammad-rework commented on src/pages/home/_what-our-clients-say.tsx
> -        ),
I used Localize in line 228. Doesn't it work?

2022-03-14 07:23 UTC, prince-deriv submitted a review, later dismissed

2022-03-14 08:09 UTC, sean-binary commented on src/pages/home/_what-our-clients-say.tsx
> -        ),
Not for the string extraction. As that is basically a node script that scans through all files and extract anything wrapped with `localize`.

2022-03-14 08:20 UTC, sean-binary commented on src/pages/home/_what-our-clients-say.tsx
> -        ),
You can refer to this for more info: https://deriv-group.slack.com/archives/G3AHMSM3P/p1575604609012800

2022-03-28 12:17 UTC, vijayasree-deriv approved these changes

2022-03-28 12:47 UTC, alamin-deriv approved these changes
LGTM

2022-03-29 02:46 UTC, sean-binary approved these changes

2022-03-29 11:06 UTC, aswathy-deriv approved these changes

2022-04-12 05:09 UTC, merged