fiona / convert derivgo to ts
binary-com/deriv-com pull request #2767
Opened 2022-03-11 15:38 UTC by fiona-deriv

Changes:

-   ...

## Type of change

-   [ ] Bug fix
-   [ ] New feature
-   [x] Update feature
-   [ ] Refactor code
-   [ ] Translation to code
-   [ ] Translation to crowdin
-   [ ] Script configuration
-   [ ] Improve performance
-   [ ] Style only
-   [ ] Dependency update
-   [ ] Documentation update
-   [ ] Release

2022-03-14 02:22 UTC, sean-binary requested changes

2022-03-14 02:22 UTC, sean-binary commented on src/pages/landing/deriv-go/_deriv-go-content.tsx
> +export type ItemsTye = {
```suggestion
export type ItemsType = {
```

2022-03-14 02:22 UTC, sean-binary commented on src/pages/landing/deriv-go/components/_tabs.tsx
> +const TabContent = styled.div<TabContentType>`
```suggestion
const TabContent = styled.div<TabContentProps>`
```

2022-03-14 02:22 UTC, sean-binary commented on src/pages/landing/deriv-go/components/_tabs.tsx
> +const Tabs = ({ children, is_reverse, className, max_width }: TabsTYpe) => {
```suggestion
const Tabs = ({ children, is_reverse, className, max_width }: TabsProps) => {
```
Should be Props for components.

2022-03-14 02:22 UTC, sean-binary commented on src/pages/landing/deriv-go/index.tsx
> +const items: ItemsTye[] = [
```suggestion
const items: ItemsType[] = [
```

2022-03-14 02:22 UTC, sean-binary commented
Please do resolve the conflicts upstream 🙏

2022-03-18 08:49 UTC, sean-binary approved these changes

2022-04-13 06:22 UTC, vijayasree-deriv commented on src/pages/landing/deriv-go/_deriv-go-content.tsx
>  DerivGoContent.propTypes = {
@fiona-deriv Shouldn't this be deleted since DerivGoContentProps is typed.

2022-04-13 06:27 UTC, vijayasree-deriv commented on src/pages/landing/deriv-go/_what-is-deriv-go.tsx
> +const items: ItemsType[] = [
@fiona-deriv could you tell me why ItemsType[] is used instead of ItemsType.

2023-02-08 03:06 UTC, closed without merging