Niloofar Sadeghi / Change deriv-go url structure
binary-com/deriv-com pull request #2805
Opened 2022-03-17 09:31 UTC by niloo-fs

Changes:

-   ...

## Type of change

-   [ ] Bug fix
-   [ ] New feature
-   [ ] Update feature
-   [ ] Refactor code
-   [ ] Translation to code
-   [ ] Translation to crowdin
-   [ ] Script configuration
-   [ ] Improve performance
-   [ ] Style only
-   [ ] Dependency update
-   [ ] Documentation update
-   [ ] Release

2022-03-17 10:51 UTC, ShuvoHabib approved these changes
LGTM

2022-03-17 10:53 UTC, habib-deriv submitted a review, later dismissed

2022-03-18 05:48 UTC, alamin-deriv submitted a review, later dismissed

2022-03-22 05:55 UTC, sean-binary requested changes
We will need to add the NGINX redirect in the deriv.com.conf file. You can follow the structure for `story`.

2022-03-28 05:18 UTC, niloo-fs commented
> NGINX

I made the changes. would u pls check it again

2022-03-28 06:03 UTC, sean-binary commented on deriv.com.conf
> +
```suggestion
    location ~* "^/([\w]{2}|zh-tw|zh-cn)/landing/deriv-go" {
        return 301 https://$http_host/$1/deriv-go/;
    }

    location /landing/deriv-go {
        return 301 https://$http_host/deriv-go/;
    }

```

2022-03-28 06:03 UTC, sean-binary commented on deriv.com.conf
> +
The original link should have `landing/` it in @niloo-fs .

2022-03-28 06:14 UTC, sean-binary approved these changes

2022-03-28 09:05 UTC, aswathy-deriv approved these changes

2022-03-29 01:37 UTC, merged