Mohsen/ updated translation.yml workflow
binary-com/deriv-com pull request #2976
Opened 2022-04-24 10:20 UTC by michio-rework

Changes:
- * updated translation.yml to be triggered on master branch
- * now key extraction will happen on pushing to msater
- * now PR creation base branch will be master instead of crowdin
- * removed getTag github action since we don't need it anymore

## Type of change

-   [ ] Bug fix
-   [ ] New feature
-   [x] Update feature
-   [ ] Refactor code
-   [ ] Translation to code
-   [ ] Translation to crowdin
-   [ ] Script configuration
-   [ ] Improve performance
-   [ ] Style only
-   [ ] Dependency update
-   [ ] Documentation update
-   [ ] Release

2022-04-24 22:07 UTC, alamin-deriv approved these changes

2022-04-25 06:15 UTC, aswathy-deriv approved these changes

2022-04-27 06:20 UTC, yashim-deriv requested changes
Can confirm with Putri if this is okay? For some cases we would probably want to batch translation for pages.

2022-04-27 08:50 UTC, michio-rework commented
> Can confirm with Putri if this is okay? For some cases we would probably want to batch translation for pages.

Sure I will ask them to look into this, thanks.

2022-08-14 10:40 UTC, closed without merging