Vijayasree/ Label color
binary-com/deriv-com pull request #3038
Opened 2022-05-12 07:42 UTC by vijayasree-deriv

Changes:

-   ...

## Type of change

-   [ ] Bug fix
-   [ ] New feature
-   [ ] Update feature
-   [ ] Refactor code
-   [ ] Translation to code
-   [ ] Translation to crowdin
-   [ ] Script configuration
-   [ ] Improve performance
-   [ ] Style only
-   [ ] Dependency update
-   [ ] Documentation update
-   [ ] Release

2022-05-12 09:22 UTC, aswathy-deriv commented on src/components/elements/affiliate-date-picker.js
> +                la
Why is this line added?

2022-05-12 09:33 UTC, vijayasree-deriv commented on src/components/elements/affiliate-date-picker.js
> +                la
this is a mistake , i'll remove it

2022-05-12 09:35 UTC, vijayasree-deriv commented on src/components/elements/affiliate-date-picker.js
> +                      color: var(--color-${({ error }) => (error ? 'red-1' : 'green')});
green is a theme color  - var(--color-green), this is the corresponding color used in the codebase.

2022-05-13 04:53 UTC, aswathy-deriv approved these changes

2022-05-14 10:13 UTC, NikitK-deriv approved these changes

2022-07-20 04:14 UTC, yashim-deriv approved these changes

2022-11-13 10:23 UTC, michio-rework requested changes
Please resolve the conflicts, thanks thanks :pray:

2022-11-14 07:36 UTC, closed without merging