Meenu/Pr 67344 meenu add appstore links dmt5 home carousel
binary-com/deriv-com pull request #3457
Opened 2022-08-05 10:18 UTC by meenakshi-deriv

Changes:

-   ...

## Type of change

-   [ ] Bug fix
-   [ ] New feature
-   [ ] Update feature
-   [ ] Refactor code
-   [ ] Translation to code
-   [ ] Translation to crowdin
-   [ ] Script configuration
-   [ ] Improve performance
-   [ ] Style only
-   [ ] Dependency update
-   [ ] Documentation update
-   [ ] Release

2022-08-05 11:12 UTC, habib-deriv approved these changes
LGTM

2022-08-08 07:52 UTC, michio-rework requested changes

2022-08-08 07:52 UTC, michio-rework commented on src/pages/home/platform-carousel/_details.tsx
> +                                key={index}
Please don't use the map index as key, it's not efficient. please check [this out](https://medium.com/wesionary-team/using-index-as-a-key-is-an-anti-pattern-in-react-8e5db3aea3a9)

2022-08-11 11:26 UTC, michio-rework submitted a review, later dismissed

2022-08-15 07:39 UTC, michio-rework approved these changes

2022-08-29 10:38 UTC, merged