onik/deriv-com_pagespeed
binary-com/deriv-com pull request #3503
Opened 2022-08-18 05:39 UTC by onik-deriv

Changes:

-   ...

## Type of change

-   [ ] Bug fix
-   [ ] New feature
-   [ ] Update feature
-   [ ] Refactor code
-   [ ] Translation to code
-   [ ] Translation to crowdin
-   [ ] Script configuration
-   [ ] Improve performance
-   [ ] Style only
-   [ ] Dependency update
-   [ ] Documentation update
-   [ ] Release

2022-08-18 05:50 UTC, shudarshon-binary commented on deriv.com.conf
> +
please commented lines that are related to configurations. you can move the module `on` to the upper side of the config as per the convention

2022-08-18 06:02 UTC, shudarshon-binary commented on deriv.com.conf
> +    }
we dont need multiple roots, there is one declared already

2022-08-18 06:11 UTC, shudarshon-binary commented on deriv.com.conf
> +    error_page   500 502 503 504  /50x.html;
we already have error_page code declared. please remove the redundant one

2022-08-18 06:25 UTC, shudarshon-binary requested changes

2022-08-18 06:25 UTC, shudarshon-binary commented on deriv.com.conf
> +    }
better to avoid this block as we have already declared error_page to 50x status codes

2022-08-18 07:01 UTC, shudarshon-binary approved these changes

2022-08-23 04:21 UTC, yashim-deriv approved these changes

2022-08-23 04:21 UTC, merged

2022-08-23 04:21 UTC, habib-deriv approved these changes