Meenu/fix: added app store links
binary-com/deriv-com pull request #3568
Opened 2022-08-30 11:15 UTC by meenakshi-deriv

Changes:

-   ...

## Type of change

-   [ ] Bug fix
-   [ ] New feature
-   [ ] Update feature
-   [ ] Refactor code
-   [ ] Translation to code
-   [ ] Translation to crowdin
-   [ ] Script configuration
-   [ ] Improve performance
-   [ ] Style only
-   [ ] Dependency update
-   [ ] Documentation update
-   [ ] Release

2022-08-30 11:30 UTC, habib-deriv submitted a review, later dismissed

2022-09-01 11:51 UTC, michio-rework requested changes

2022-09-01 11:51 UTC, michio-rework commented on src/pages/dmt5/_download-app.tsx
> +                                external="true"
`external` should be `boolean` please update all of them and check every file for `typescript` issues, thanks thanks :pray:

2022-09-22 13:58 UTC, habib-deriv approved these changes

2022-09-22 13:58 UTC, merged