Mitra/feat: add whatsapp button
binary-com/deriv-com pull request #3625
Opened 2022-09-13 05:06 UTC by mitra-deriv

Changes:

-   ...

## Type of change

-   [ ] Bug fix
-   [x] New feature
-   [ ] Update feature
-   [ ] Refactor code
-   [ ] Translation to code
-   [ ] Translation to crowdin
-   [ ] Script configuration
-   [ ] Improve performance
-   [ ] Style only
-   [ ] Dependency update
-   [ ] Documentation update
-   [ ] Release

2022-09-15 07:36 UTC, farzin-fs commented on src/pages/help-centre/_didnt-find-answer.tsx
> +    debugger
👀

2022-09-15 07:37 UTC, michio-rework requested changes

2022-09-15 07:37 UTC, michio-rework commented on src/pages/help-centre/_didnt-find-answer.tsx
> +    // eslint-disable-next-line no-debugger
please remove these lines, `debugger` and disable eslint, thanks :pray:

2022-09-15 07:37 UTC, michio-rework commented on src/pages/help-centre/_didnt-find-answer.tsx
> +                            secondary="true"
I think this should be `boolean` can you check it out please? :pray:

2022-09-15 07:45 UTC, farzin-fs approved these changes

2022-09-15 07:49 UTC, michio-rework approved these changes

2022-09-15 08:01 UTC, sandeep-deriv approved these changes

2022-09-15 08:31 UTC, yashim-deriv approved these changes

2022-09-19 09:18 UTC, prince-deriv approved these changes

2022-09-19 09:20 UTC, farzin-fs approved these changes

2022-09-22 13:59 UTC, merged