Eduard / Attribute loading not allowed on element div (loading isn't an attribute, it's a props)
binary-com/deriv-com pull request #3658
Opened 2022-09-20 15:48 UTC by eduard-deriv

Changes:

-   removed unused code in ImageWrapper (never changes `disable_transition` props value to `true`, always uses default `disable_transition` props value, `loading` value changes due to `[data-main-image]`. Both conditions must be met, but this behavior will never happen)

## Type of change

-   [ ] Bug fix
-   [ ] New feature
-   [ ] Update feature
-   [ X ] Refactor code
-   [ ] Translation to code
-   [ ] Translation to crowdin
-   [ ] Script configuration
-   [ ] Improve performance
-   [ ] Style only
-   [ ] Dependency update
-   [ ] Documentation update
-   [ ] Release

2022-09-21 02:11 UTC, yashim-deriv requested changes

2022-09-21 02:11 UTC, yashim-deriv commented on src/components/elements/query-image.tsx
> -                loading={loading}
The `loading` property is still used in multiple places. Some functionality will break if you remove this property. 

A few explanation for this property: It is an extension of the base type of `gatsby-plugin-image` https://www.gatsbyjs.com/docs/reference/built-in-components/gatsby-plugin-image/#shared-props

You can check this by searching for `loading="eager"`

2022-09-21 02:11 UTC, yashim-deriv commented on src/components/elements/query-image.tsx
> -    loading: 'eager' | 'lazy'
Can you remove `width`, `height`, `className` and other properties that are already declared by the `IGatsbyImageData`? Change this to an interface and extend 

```
export interface QueryImageProps extends IGatsbyImageData
```

2022-09-22 02:36 UTC, yashim-deriv approved these changes

2022-09-22 05:56 UTC, niloo-fs approved these changes
LGTM

2022-10-14 11:28 UTC, merged