MohammadH/ Fix some ts errors
binary-com/deriv-com pull request #3761
Opened 2022-10-21 17:51 UTC by mohammad-rework

Changes:

-   ...

## Type of change

-   [ ] Bug fix
-   [ ] New feature
-   [ ] Update feature
-   [ ] Refactor code
-   [ ] Translation to code
-   [ ] Translation to crowdin
-   [ ] Script configuration
-   [ ] Improve performance
-   [ ] Style only
-   [ ] Dependency update
-   [ ] Documentation update
-   [ ] Release

2022-10-23 06:23 UTC, michio-rework commented on src/common/validation.ts
> +}
```sugesstion
type TValidationHandler = (input: string, message?: string) => string | null
type TValidationMethods = "email" | "name" | "required" | "url" | "number" | "alphabetic"
type TValidationType = {
    [key in TValidationMethos] : TValidationHandler
}
```

just a suggestion, you can ignore this.

2022-10-23 06:24 UTC, michio-rework reviewed
please check the suggestion, ignore it if it's not cool with you.

2022-11-02 08:49 UTC, NikitK-deriv approved these changes

2022-11-06 10:55 UTC, michio-rework requested changes
please resolve conflicts :pray:

2022-11-13 09:57 UTC, michio-rework approved these changes

2022-11-13 10:48 UTC, merged