MohammadH/ Remove verbose code and use map for redundant items
binary-com/deriv-com pull request #3762
Opened 2022-10-23 07:03 UTC by mohammad-rework

Changes:

-   ...

## Type of change

-   [ ] Bug fix
-   [ ] New feature
-   [ ] Update feature
-   [x] Refactor code
-   [ ] Translation to code
-   [ ] Translation to crowdin
-   [ ] Script configuration
-   [ ] Improve performance
-   [ ] Style only
-   [ ] Dependency update
-   [ ] Documentation update
-   [ ] Release

2022-11-02 08:40 UTC, NikitK-deriv submitted a review, later dismissed

2022-11-06 10:53 UTC, michio-rework requested changes

2022-11-06 10:53 UTC, michio-rework commented on src/components/custom/_dhero-2.tsx
> +type HeroItemsType = {
```suggestion
type HeroItemsType = {
    url: string
    image: string
    alt: string
}
const HeroItems: HeroItemsType[] = [...]
```

2022-11-06 10:53 UTC, michio-rework commented on src/components/custom/_signup-public.tsx
> +
```suggestion
type SocialButtonContent = {
    provider: string
    id: string
    img: string
}
const social_button_content: SocialButtonContent[] = [...]
```

2022-11-07 09:58 UTC, michio-rework approved these changes

2022-11-13 10:45 UTC, merged