Konstantinos / Synthetic/Derived should not be available for UK
binary-com/deriv-com pull request #3778
Opened 2022-10-26 09:31 UTC by konstantinosG-deriv

Changes:

-   ...

## Type of change

-   [x] Bug fix
-   [ ] New feature
-   [ ] Update feature
-   [ ] Refactor code
-   [ ] Translation to code
-   [ ] Translation to crowdin
-   [ ] Script configuration
-   [ ] Improve performance
-   [ ] Style only
-   [ ] Dependency update
-   [ ] Documentation update
-   [ ] Release

2022-10-26 09:55 UTC, habib-deriv submitted a review, later dismissed

2022-11-02 08:17 UTC, NikitK-deriv approved these changes

2022-11-06 10:49 UTC, michio-rework approved these changes

2022-11-06 10:50 UTC, michio-rework requested changes
please resolve conflicts :pray:

2022-11-07 01:49 UTC, mitra-deriv commented
@konstantinosG-deriv I think it’s better to close this PR as it is not needed anymore thanks 🙏

2022-11-07 07:56 UTC, closed without merging