chore: remove deriv ez
binary-com/deriv-com pull request #5762
Opened 2023-10-10 11:53 UTC by mayuran-deriv

Changes:

-   ...

## Type of change

-   [ ] Bug fix
-   [ ] New feature
-   [ ] Update feature
-   [ ] Refactor code
-   [ ] Translation to code
-   [ ] Translation to crowdin
-   [ ] Script configuration
-   [ ] Improve performance
-   [ ] Style only
-   [ ] Dependency update
-   [ ] Documentation update
-   [ ] Release

2023-10-10 12:18 UTC, aswathy-deriv approved these changes

2023-10-11 02:48 UTC, hasan-deriv reviewed
Check the images and icons if they are not been using anywhere else then remove those files as well.

2023-10-11 04:41 UTC, mitra-deriv requested changes

2023-10-11 04:41 UTC, mitra-deriv commented on src/pages/trading-specification/components/_available-platform.tsx
> -                                ) : null}
Hi , Lets remove line [65](https://github.com/binary-com/deriv-com/pull/5762/files#diff-d5e82e3bcd9954e86a254b94cf57db51274020e3da50925949d6dd4de9156566L65), [68](https://github.com/binary-com/deriv-com/pull/5762/files#diff-d5e82e3bcd9954e86a254b94cf57db51274020e3da50925949d6dd4de9156566L69) as well  , if it's not needed @mayuran-deriv 🫡

2023-10-11 14:36 UTC, mitra-deriv approved these changes

2023-10-12 02:02 UTC, hasan-deriv approved these changes

2023-10-19 12:29 UTC, closed without merging