refactor: To separate docker and k8s notification
binary-com/deriv-com pull request #6434
Opened 2024-01-04 09:26 UTC by yaswanth-deriv

Changes:

-   Separated Docker and Kubernetes Status notification from Cloudflare Pages deployment slack notification in deriv-com repo

## Type of change

-   [ ] Bug fix
-   [ ] New feature
-   [ ] Update feature
-   [X] Refactor code
-   [ ] Translation to code
-   [ ] Translation to crowdin
-   [ ] Script configuration
-   [ ] Improve performance
-   [ ] Style only
-   [ ] Dependency update
-   [ ] Documentation update
-   [X] Release

2024-01-09 10:17 UTC, ali-hosseini-deriv requested changes

2024-01-09 10:17 UTC, ali-hosseini-deriv commented on .github/workflows/production.yml
>              - name: Deploy 🚀
```suggestion
            - name: Deploy 🚀
              id: build_and_push_docker_image
```

2024-01-09 10:17 UTC, ali-hosseini-deriv commented on .github/workflows/production.yml
>                if: always()
```suggestion
              if: ${{ steps.build_and_push_docker_image.outcome != 'success' }}
```

2024-01-10 03:28 UTC, ali-hosseini-deriv approved these changes

2024-01-10 03:41 UTC, habib-deriv approved these changes
LGTM

2024-01-10 03:41 UTC, merged