Konstantinos/DPROD-3000/[FE] Revamp Regulatory Information page (ROW)
binary-com/deriv-com pull request #6940
Opened 2024-01-31 13:00 UTC by konstantinosG-deriv

Changes:

Update Regulatory Page for ROW with Quill Design.

## Type of change

-   [ ] Bug fix
-   [ ] New feature
-   [x] Update feature
-   [ ] Refactor code
-   [ ] Translation to code
-   [ ] Translation to crowdin
-   [ ] Script configuration
-   [ ] Improve performance
-   [ ] Style only
-   [ ] Dependency update
-   [ ] Documentation update
-   [ ] Release

2024-01-31 16:05 UTC, dan-deriv approved these changes

2024-02-01 02:11 UTC, hasan-deriv requested changes
Still old components are here. Need to change those components to quill.

2024-02-06 06:45 UTC, aswathy-deriv commented on src/pages/regulatory/_eu-grid.tsx
> +                    <FlagAustriaIcon className={styles.icon} fill="#000000b8" />
Can you convert this by looping in array as all the components are repeating.We can use an array something like this 
`const countries = [
  { href: "/regulatory/countries/Greece.pdf", icon: <FlagGreeceIcon className={styles.icon} iconSize="md" fill="#000000b8" />, text: "_t_Greece_t_" },
  { href: "/regulatory/countries/Hungary.pdf", icon: <FlagHungaryIcon className={styles.icon} iconSize="md" fill="#000000b8" />, text: "_t_Hungary_t_" },
  { href: "/regulatory/countries/Italy.pdf", icon: <FlagItalyIcon className={styles.icon} iconSize="md" fill="#000000b8" />, text: "_t_Italy_t_" }
];`

2024-02-06 06:49 UTC, aswathy-deriv commented on src/pages/regulatory/index.tsx
> +                                                                    href="/regulatory/RTS28-2022.pdf"
Similarly here by looping via array if the components are repeating

2024-02-06 09:55 UTC, aswathy-deriv submitted a review, later dismissed

2024-02-06 10:20 UTC, hasan-deriv commented on src/pages/regulatory/eu_grid.module.scss
Can you try only responsive css to move in scss module and rest of them in tailwind?

2024-02-23 09:25 UTC, closed without merging

2024-02-23 09:26 UTC, konstantinosG-deriv commented
Opening new PR with resolved conflicts