[Translation] MARK-1013/ Fix validation in Partners Signup Form [FE]
binary-com/deriv-com pull request #7050
Opened 2024-02-12 09:17 UTC by NikitK-deriv

Changes:

Right now we have few unhandled errors while users trying to sign up as partners
This fix updating regex rules in form side to make them the same as third-party service

Updating existing regex with rules from third-party service

## Type of change

-   [x] Bug fix
-   [ ] New feature
-   [x] Update feature
-   [ ] Refactor code
-   [ ] Translation to code
-   [ ] Translation to crowdin
-   [ ] Script configuration
-   [ ] Improve performance
-   [ ] Style only
-   [ ] Dependency update
-   [ ] Documentation update
-   [ ] Release

2024-02-15 06:25 UTC, prince-deriv requested changes

2024-02-15 06:25 UTC, prince-deriv commented on src/pages/signup-affiliates/index.tsx
```suggestion
const ParentWrapper = styled.div<{ isPopupOpen?: boolean }>`
    block-size: calc(100svh - 70px);
    background-image: url(${Map});
    background-repeat: no-repeat;
    background-position: bottom;
    overflow: ${({ isPopupOpen }) => (isPopupOpen ? 'hidden' : 'auto')};

```

2024-02-15 06:29 UTC, NikitK-deriv commented on src/pages/signup-affiliates/index.tsx
Resolved @prince-deriv , thanks

2024-02-15 06:31 UTC, prince-deriv approved these changes

2024-02-15 08:17 UTC, eduard-deriv approved these changes

2024-02-20 08:13 UTC, fasihali-deriv approved these changes

2024-02-20 08:16 UTC, merged