perf: deleting unused pages
binary-com/deriv-com pull request #7073
Opened 2024-02-15 11:44 UTC by agrim-deriv

Changes:

Deleting the unused landing pages

## Type of change

-   [ ] Bug fix
-   [ ] New feature
-   [ ] Update feature
-   [ ] Refactor code
-   [ ] Translation to code
-   [ ] Translation to crowdin
-   [ ] Script configuration
-   [x] Improve performance
-   [ ] Style only
-   [ ] Dependency update
-   [ ] Documentation update
-   [ ] Release

2024-02-16 05:55 UTC, prince-deriv approved these changes

2024-02-20 12:33 UTC, meenakshi-deriv approved these changes

2024-02-21 01:54 UTC, habib-deriv submitted a review, later dismissed

2024-02-21 02:04 UTC, fasihali-deriv approved these changes
Hi @agrim-deriv please help to update the PR title. 
Thank you

2024-02-21 07:10 UTC, behnaz-deriv requested changes
Thanks Agrim to remove these old landing pages, pls also help to remove
 svg files that used in these index files and not use anymore as well eg images/svg/dmt5/dmt5-bg.svg  🙏

2024-02-21 08:03 UTC, habib-deriv submitted a review, later dismissed

2024-02-21 08:12 UTC, meenakshi-deriv submitted a review, later dismissed

2024-02-21 08:27 UTC, behnaz-deriv approved these changes

2024-02-21 08:53 UTC, behnaz-deriv approved these changes

2024-03-14 09:19 UTC, aswathy-deriv approved these changes

2024-03-14 09:20 UTC, merged