Translation 008866 accumulator branch
binary-com/deriv-com pull request #7208
Opened 2024-02-29 13:27 UTC by mayuran-deriv

Changes:

-   ...

## Type of change

-   [ ] Bug fix
-   [ ] New feature
-   [ ] Update feature
-   [ ] Refactor code
-   [ ] Translation to code
-   [ ] Translation to crowdin
-   [ ] Script configuration
-   [ ] Improve performance
-   [ ] Style only
-   [ ] Dependency update
-   [ ] Documentation update
-   [ ] Release

2024-03-01 09:32 UTC, hasan-deriv requested changes

2024-03-01 09:32 UTC, hasan-deriv commented on src/features/pages/options/accumulator/data.tsx
> +                }}
Use this link -> https://github.com/binary-com/deriv-com/blob/master/src/features/components/quill/shared-link/index.tsx

2024-03-01 09:32 UTC, hasan-deriv commented on src/features/pages/options/accumulator/data.tsx
> +        icon: <Image src={TickDuration} width="48" height="48" />,
Don't use the atomic component... We have plan to remove atomic component and css once we completely revamp.

2024-03-01 09:55 UTC, habib-deriv approved these changes

2024-03-01 10:28 UTC, hasan-deriv approved these changes

2024-03-12 06:00 UTC, aswathy-deriv approved these changes

2024-03-12 06:02 UTC, merged