Agrim/DPROD-2013/fix: redirection to traders hub
binary-com/deriv-com pull request #7267
Opened 2024-03-08 06:39 UTC by agrim-deriv

Changes:

Changing the redirections of MT5 dashboard. Navigating now to traders hub. 

## Type of change

-   [ ] Bug fix
-   [ ] New feature
-   [ ] Update feature
-   [ ] Refactor code
-   [ ] Translation to code
-   [ ] Translation to crowdin
-   [ ] Script configuration
-   [ ] Improve performance
-   [ ] Style only
-   [ ] Dependency update
-   [ ] Documentation update
-   [ ] Release

2024-03-08 06:49 UTC, habib-deriv commented on src/pages/dmt5-trading-signals/_how-to.tsx
> +                        to="https://app.deriv.com/appstore/traders-hub"
Let's have the url from constants.ts

2024-03-08 06:49 UTC, habib-deriv requested changes
Let's have the url from constants.ts

2024-03-08 08:03 UTC, habib-deriv submitted a review, later dismissed

2024-03-10 11:05 UTC, mayuran-deriv approved these changes

2024-03-14 08:25 UTC, aswathy-deriv approved these changes

2024-03-14 08:26 UTC, merged